name: ubuntu-mate-pi
base: core20
version: git
summary: Support information for users of Ubuntu MATE for the Pi
description: |
  Simple script to present support and contact information for users of
  the Ubuntu MATE images for Raspberry Pi.

architectures:
  - build-on: armhf
  - build-on: arm64

grade: stable
confinement: strict

parts:
  ubuntu-mate-pi:
    plugin: dump
    source: .

apps:
  ubuntu-mate-pi:
    command: ubuntu-mate-pi
